// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutauthTasksIdImport } from './routes/_layout/_auth/tasks.$id'

// Create Virtual Routes

const LayoutComponentImport = new FileRoute('/_layout').createRoute()
const LayoutIndexComponentImport = new FileRoute('/_layout/').createRoute()
const LayoutLoginComponentImport = new FileRoute('/_layout/login').createRoute()
const LayoutauthComponentImport = new FileRoute('/_layout/_auth').createRoute()
const LayoutauthTasksComponentImport = new FileRoute(
  '/_layout/_auth/tasks',
).createRoute()
const LayoutauthTasksNewComponentImport = new FileRoute(
  '/_layout/_auth/tasks/new',
).createRoute()

// Create/Update Routes

const LayoutComponentRoute = LayoutComponentImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout.component'),
    'component',
  ),
})

const LayoutIndexComponentRoute = LayoutIndexComponentImport.update({
  path: '/',
  getParentRoute: () => LayoutComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/index.component'),
    'component',
  ),
})

const LayoutLoginComponentRoute = LayoutLoginComponentImport.update({
  path: '/login',
  getParentRoute: () => LayoutComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/login.component'),
    'component',
  ),
})

const LayoutauthComponentRoute = LayoutauthComponentImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/_auth.component'),
    'component',
  ),
})

const LayoutauthTasksComponentRoute = LayoutauthTasksComponentImport.update({
  path: '/tasks',
  getParentRoute: () => LayoutauthComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/_auth/tasks.component'),
    'component',
  ),
})

const LayoutauthTasksNewComponentRoute =
  LayoutauthTasksNewComponentImport.update({
    path: '/new',
    getParentRoute: () => LayoutauthTasksComponentRoute,
  } as any).update({
    component: lazyRouteComponent(
      () => import('./routes/_layout/_auth/tasks.new.component'),
      'component',
    ),
  })

const LayoutauthTasksIdRoute = LayoutauthTasksIdImport.update({
  path: '/$id',
  getParentRoute: () => LayoutauthTasksComponentRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/_auth/tasks.$id.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutComponentImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      preLoaderRoute: typeof LayoutauthComponentImport
      parentRoute: typeof LayoutComponentImport
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginComponentImport
      parentRoute: typeof LayoutComponentImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexComponentImport
      parentRoute: typeof LayoutComponentImport
    }
    '/_layout/_auth/tasks': {
      preLoaderRoute: typeof LayoutauthTasksComponentImport
      parentRoute: typeof LayoutauthComponentImport
    }
    '/_layout/_auth/tasks/$id': {
      preLoaderRoute: typeof LayoutauthTasksIdImport
      parentRoute: typeof LayoutauthTasksComponentImport
    }
    '/_layout/_auth/tasks/new': {
      preLoaderRoute: typeof LayoutauthTasksNewComponentImport
      parentRoute: typeof LayoutauthTasksComponentImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutComponentRoute.addChildren([
    LayoutauthComponentRoute.addChildren([
      LayoutauthTasksComponentRoute.addChildren([
        LayoutauthTasksIdRoute,
        LayoutauthTasksNewComponentRoute,
      ]),
    ]),
    LayoutLoginComponentRoute,
    LayoutIndexComponentRoute,
  ]),
])
